export { default as NavBar } from './navbar/NavBar'
export { default as Hero } from './hero/Hero'
export { default as About } from './about/About'
export { default as Offer } from './offer/Offer'
export { default as Footer } from './footer/Footer'
export { default as Classes } from './classes/Classes'
export { default as Testimonial } from './testimonial/Testimonial'